#!/usr/bin/perl
# common_bed.pl by YWL on 2/20/13
# input a file generated by intersectBed -wo
# clean up bed file by taking only common interval of overlap

use strict; use warnings;

die "usage: common_bed.pl <bed file generated by intersectBed -wo>\n" unless @ARGV == 1;
open (IN, $ARGV[0]) or die "error opening $ARGV[0]\n";

while (my $line = <IN>)
{
	chomp $line;
	my ($chr, $start1, $end1, $start2, $end2) = $line =~ m/(\w+)\t(\d+)\t(\d+)\t\w+\t(\d+)\t(\d+)/;

	print "$chr\t";
	# print the overlap (narrowest region)
	if ($start1 >= $start2)
	{
		print "$start1\t";
	}
	else
	{
		print "$start2\t";
	}
	if ($end1 <= $end2)
	{
		print "$end1\n";
	}
	else
	{
		print "$end2\n";
	}
}

close IN;
