#!/usr/bin/perl
# insilicodigest.pl by Yoong Wearn Lim
# compile Digest file generated by Digest.java
# output fragment coordinates generated by the 5 enzyme digest used in DRIP

use strict; use warnings;

die "usage: insilicodigest.pl <Digest file>" unless @ARGV == 1;
my ($file) = $ARGV[0];

open (IN, $file) or die "Fail to open $file\n";

my @coor;
my %coor;
my %seen;
my $start;
my $stop;
my $chr;

while (my $line = <IN>)
{
	chomp $line;
	($chr) = $line =~ m/^chr(\S+)/;
	($start, $stop) = $line =~ m/^chr\S+\t\w+\t(\d+)\t(\d+)/;
	
	if (!exists $seen{$chr}{$start})
	{
		push (@{$coor{$chr}}, $start);
		$seen{$chr}{$start} = 1;
	}
	
	if (!exists $seen{$chr}{$stop})
	{
		push (@{$coor{$chr}}, $stop);
		$seen{$chr}{$stop} = 1;
	}
	
	#print "chr$chr	$start	$stop\n";
	#push (@coor, $start, $stop);
}



foreach $chr (sort {$a <=> $b} keys %coor)
{
	@{$coor{$chr}} = sort { $a <=> $b} @{$coor{$chr}};
	
	for (my $i = 0; $i < @{$coor{$chr}} - 1; $i++)
	{
		print "chr$chr	", $coor{$chr}[$i]+1, "	$coor{$chr}[$i+1]\n";
	}
}
